### ISSUE TITLE
Unsupported Hyperparamters???

### ISSUE THREAD

**Issue by farzad-xgen** [aws/sagemaker-xgboost-container#113]
When you get the image on SageMaker using *get_image_uri*, it supports **num_parallel_tree** and **epoch** hyperparameters. There's no *epoch* in XGBoost documentation, but *num_parallel_tree* is there. When I tried to use **mme** version of the container (from both mme and mme_support_xgb1.0 branches), I couldn't find the *num_parallel_tree* and setting it causes an error in the training job.

I think this one, **num_parallel_tree** is missing and is needed to be added, if possible.

**Comment by aws-patlin** [comment]
Hi @farzad-xgen,

I couldn't find where the `epoch` hyperparameter is being supported. Do you mean that you're able to pass this in as a hyperparameter? Hyperparameters are only validated by the container, not by the SageMaker Python SDK or boto3.

Regarding `num_parallel_tree`, it does look like we missed whitelisting this hyperparameter. Thank you for bringing this to our attention! We will work on having a fix soon.

**Comment by aws-patlin** [comment]
We've added support for this hyperparameter a while ago. Closing this issue. Feel free to open it again if you're still having trouble!

**Comment by djwbamboo** [comment]
I'm still observing the following when calling `create_hyper_parameter_tuning_job`:

`ClientError: An error occurred (ValidationException) when calling the CreateHyperParameterTuningJob operation: The hyperparameter tuning job that you requested has the following untunable hyperparameters: [num_parallel_tree]. For the algorithm, 141502667606.dkr.ecr.eu-west-1.amazonaws.com/sagemaker-xgboost:1.5-1, you can tune only [colsample_bytree, lambda, eta, max_depth, alpha, colsample_bynode, num_round, colsample_bylevel, subsample, min_child_weight, max_delta_step, gamma]. Delete untunable hyperparameters.`

**Comment by aws-patlin** [comment]
Hi @djwbamboo, thanks for pointing this out. There is a different SageMaker configuration that defines tunable hyperparameters for the hyperparameter tuning jobs. I will make sure the team updates this.

**Comment by djwbamboo** [comment]
I noticed this parameter is tuneable through the web interface, just not though the api, so I guess that eliminates it being a container problem. Thanks for forwarding it to the appropriate team.

**Comment by haixiw** [comment]
Hi, @djwbamboo , Thanks for calling out this. We are rolling out the updated configuration so that you can tune this parameter through `create_hyper_parameter_tuning_job`. I will update here when the patch has been deployed worldwide.
