### ISSUE TITLE
KeyError: 'S3DistributionType' when trying to use the container via a SageMaker local-mode estimator

### ISSUE THREAD

**Issue by tlienart** [aws/sagemaker-xgboost-container#155]
Hello,

I built the image with version `1.2-1` and pushed it to ECR and would like to call it via a SageMaker estimator in local mode; something like: 

```python
xgb = Estimator(
    image_uri=ECR_URI
    role='arn:aws:iam::111111111111:role/service-role/role-name',
    instance_count=1,
    hyperparameters={
        "objective": "reg:squarederror",
        "num_round": 10,
    },
    instance_type="local",
    input_mode="File",
    output_path='file://.',
)

train_dataset = TrainingInput(f'file://{local_train}', content_type="text/csv")

xgb.fit({"train": train_dataset}, wait=True)
```

This syntax works fine with simple custom-built images. For experimentation; I'd like to also use it with an image built from the current repo. But when running this I get:

```
(...)
INFO:sagemaker_xgboost_container.training:Running XGBoost Sagemaker in algorithm mode
ERROR:sagemaker-containers:Reporting training FAILURE
ERROR:sagemaker-containers:framework error: 
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_trainer.py", line 84, in train
    entrypoint()
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_xgboost_container/training.py", line 94, in main
    train(framework.training_env())
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_xgboost_container/training.py", line 90, in train
    run_algorithm_mode()
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_xgboost_container/training.py", line 68, in run_algorithm_mode
    checkpoint_config=checkpoint_config
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_xgboost_container/algorithm_mode/train.py", line 115, in sagemaker_train
    validated_data_config = channels.validate(data_config)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_algorithm_toolkit/channel_validation.py", line 106, in validate
    channel_obj.validate(value)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_algorithm_toolkit/channel_validation.py", line 52, in validate
    if (value[CONTENT_TYPE], value[TRAINING_INPUT_MODE], value[S3_DIST_TYPE]) not in self.supported:
KeyError: 'S3DistributionType'
(...)
```

I tried specifying `distribution="FullyReplicated"` in the `TrainingInput` but got the same error. Any guidance on what I may have done wrong?

Thanks a lot in advance

**Edit**: I'm using SageMaker 2.19.

**Comment by iyerr3** [comment]
Can you try `S3DistributionType='FullyReplicated'` in the `TrainingInput`? 
You shouldn't have to do this since it has a default value but I'm hoping it unblocks you while we look into the issue.

**Comment by tlienart** [comment]
Thanks a lot, `S3DistributionType` is not a valid keyword for `TrainingInput`, I did try `distribution='FullyReplicated` but the issue remains.

**Comment by tlienart** [comment]
@iyerr3 or other, any idea what else I could try here? Thanks!

**Comment by lihaife** [comment]
@iyerr3 This is probably the root cause of failure. As shown in https://github.com/aws/sagemaker-python-sdk/blob/267f2935205da1167b917cba3172b47773af7295/src/sagemaker/local/local_session.py#L537-L552, `file_input` doesn't set `S3DistributionType`. It makes sense as the uri is not S3.

But in `sagemaker_algorithm_toolkit.channel_validation.py` (line 52), we always check if the key S3_DIST_TYPE exists:
```
        if (value[CONTENT_TYPE], value[TRAINING_INPUT_MODE], value[S3_DIST_TYPE]) not in self.supported:
            raise exc.UserError("Channel configuration for '{}' channel is not supported: {}".format(self.name, value))
```

Looking around the code, I feel that we always assume that the input is S3. Even for so call file mode, EASE still need to know S3_DIST_TYPE so that it knows how to copy the data. Doesn't it mean that XGB doesn't support local mode?

**Comment by lihaife** [comment]
@tlienart In Autopilot, we always use pipe mode because EASE reused cluster doesn't support file mode. So I suggest that we follow the pattern in AP2. That is, always use S3 as input type.

**Comment by tlienart** [comment]
Thanks Haifeng, makes sense,  I'll try that

**Comment by tlienart** [comment]
Unfortunately this still fails (with the same error), even when the path given is an s3 uri. I've tried several approach but all fail. The basic one for reproducibility: 

```
xgb.fit({"train": 's3://bucket/path/to/data.csv'}, wait=True)
```
