### ISSUE TITLE
How to use XGboost in script mode with CreateTrainingJob API?

### ISSUE THREAD

**Issue by eaishwa** [aws/sagemaker-xgboost-container#160]
I want to invoke CreateTrainingJob API using XGBoost container in script mode. Is it even possible? Otherwise, is it feasible to pass an estimator object (sagemaker.xgboost.estimator.XGBoost) to create training job API? I want to use XGBoost image with my own entry_point script and invoke training job from a lambda function. I do not want to extend the container for this purpose and build my own docker. Any help is appreciated. Thanks in advance

**Comment by iyerr3** [comment]
The script mode is a regular python script with the boto3 preinstalled. You should be able to call that api from the container. Are you having issues with running this?

**Comment by eaishwa** [comment]
@iyerr3 The create training job API https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateTrainingJob.html takes in image_uri as input, whereas for script mode I would create an estimator object like the following - 
```
from sagemaker.xgboost.estimator import XGBoost
xgb_estimator = XGBoost(
    entry_point="mytrainfolder/custom_train.py",
    role=role,
    instance_count=1,
    instance_type=training_instance_type,
    framework_version="1.0-1",
    output_path=model_path,
)
```
Wondering how to call CreateTrainingJob by passing the above estimator. In other words, I do not want to use the in-built XGBoost container image_uri directly with CreateTrainingJob because I want to run my own entry_point script like the above. Please let me know if my question is kind of unclear. Thank you for looking into this request.

**Comment by edwardjkim** [comment]
I'm not sure if I'm understanding the use case correctly, but from the description, it sounds like you want to use 1) `CreateTrainingJob`, 2) the unmodified SageMaker XGBoost container, and 3) script mode. This should be possible to do by using `sagemaker_submit_directory` and `sagemaker_program` hyperparameters in [HyperParameters](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateTrainingJob.html#sagemaker-CreateTrainingJob-request-HyperParameters). Note that you will need to upload a .tar.gz to an S3 location.

```python3
training_params = {
    "AlgorithmSpecification": {
        "TrainingImage": "<ecr_path>/sagemaker-xgboost:1.2-1",
        ...
    },
    ...
    "HyperParameters": {
        "sagemaker_program": "train.py.",
        "sagemaker_submit_directory": "s3://.../code.tar.gz"
}
sagemaker = boto3.client(service_name='sagemaker')
sagemaker.create_training_job(**training_params)
```

**Comment by eaishwa** [comment]
@edwardjkim Thank you for pointing me to this. This is exactly what I was looking for.

**Comment by iyerr3** [comment]
@eaishwa Will ask same question as @edwardjkim: What's the use case for doing this with boto3 instead of the Python Estimator? If it's a common-enough situation, I would rather we document it as an example.

**Comment by eaishwa** [comment]
@iyerr3 Sorry did not notice the follow up question that @edwardjkim left. I am working on automating model retrain and wanted to schedule training job via lambda or step function. I looked at [this page](https://docs.aws.amazon.com/step-functions/latest/dg/connect-sagemaker.html) first and saw `CreateTrainingJob` supported in step function, but later today afternoon found out that I can use the [Python TrainingStep](https://aws-step-functions-data-science-sdk.readthedocs.io/en/stable/sagemaker.html#stepfunctions.steps.sagemaker.TrainingStep) to achieve what I wanted to anyway (use the Estimator).
