### ISSUE TITLE
XGBoost 1.3.0 in SageMaker

### ISSUE THREAD

**Issue by zronaghi** [aws/sagemaker-xgboost-container#184]
Any plans to update to 1.3? We're using GPU TreeSHAP and it's available in this version. Currently using our custom container but wondering if there's a roadmap for updating the official SageMaker XGB image?

**Comment by tcru14** [comment]
Hi, this has been updated to 1.3.

**Comment by zronaghi** [comment]
Great, thanks! Just saw the PR here: https://github.com/aws/sagemaker-xgboost-container/pull/192
