### ISSUE TITLE
Need support for XGBoost 1.5.2

### ISSUE THREAD

**Issue by ramab1988** [aws/sagemaker-xgboost-container#237]
Hi!

Can we please add support for XGBoost 1.5.2 (the latest release as of now)? It has a couple of bug fixes & optimizations.

Thanks!

**Comment by awsbmillare** [comment]
Thank you for the request. Your feedback is being used to decide what we will prioritize. Stay tuned

**Comment by haixiw** [comment]
we have supported xgboost 1.5.2 with container version 1.5-1
