### ISSUE TITLE
latest image and monotonicity constraint

### ISSUE THREAD

**Issue by csetzkorn** [aws/sagemaker-xgboost-container#287]
Hi all,

I assume that when I use:

`image_uri=sagemaker.image_uris.retrieve("xgboost", region_name, "latest")`

It pulls the latest image from here (this repo)?

I can then be used in code along those lines:

```
xgb = sagemaker.estimator.Estimator(image_uri=image_uri, role=role_arn,
                                          instance_count=1, 
                                          instance_type='ml.m5.2xlarge',
                                          #instance_type='local', 
                                          volume_size=1, # 1 GB 
                                          output_path=output_path, base_job_name="test-monotonic")

# https://github.com/aws/sagemaker-xgboost-container/issues/120
xgb.set_hyperparameters(
        max_depth=10,
        num_round=30,
        nthread=2,
        seed=42,
        objective='count:poisson',
        # https://xgboost.readthedocs.io/en/stable/treemethod.html
        tree_method='hist', 
        eval_metric='rmse',
        # https://xgboost.readthedocs.io/en/stable/tutorials/monotonic.html
        # bottom of page
        monotone_constraints='(0,-1,0)')

xgb.fit({'train': s3_input_train, 'validation': s3_input_val})
```

This works fine. However, when I try to load the produced model (downloaded locally) like this:

```
local_model_path = "model.tar.gz"
with tarfile.open(local_model_path) as tar:
    tar.extractall()

model = xgb.XGBRegressor() 
model.load_model('xgboost-model') 
```

I get:

```
  File "C:\Python\Python310\lib\site-packages\xgboost\sklearn.py", line 736, in load_model
    self.get_booster().load_model(fname)
  File "C:\Python\Python310\lib\site-packages\xgboost\core.py", line 2249, in load_model
    _check_call(_LIB.XGBoosterLoadModel(
  File "C:\Python\Python310\lib\site-packages\xgboost\core.py", line 203, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: string too long
```

I am not sure what is wrong. Maybe my local package version of XGBoost is out of synch or something has changed in how the model is persisted (there was a different way of doing it in the past).

Any pointers very much appreciated. Thanks!

**Comment by mabunday** [comment]
It's confusing, but you need to specify the exact framework version for the image tag and not "latest". Check out this documentation page for more details: https://docs.aws.amazon.com/sagemaker/latest/dg/xgboost.html

I would try with `image_uris.retrieve(framework='xgboost',region=region_name,version='1.5-1')`


>When you retrieve the SageMaker XGBoost image URI, do not use :latest or :1 for the image URI tag. You must specify one of the Supported versions to choose the SageMaker-managed XGBoost container with the native XGBoost package version that you want to use. To find the package version migrated into the SageMaker XGBoost containers, see [Docker Registry Paths and Example Code](https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-algo-docker-registry-paths.html), choose your AWS Region, and navigate to the XGBoost (algorithm) section.

**Comment by mabunday** [comment]
Please use https://docs.aws.amazon.com/sagemaker/latest/dg/xgboost.html#xgboost-supported-versions as the source of truth going forward. I'll also take up some action items to improve the clarity in this repository, too.
