### ISSUE TITLE
Sagemaker endpoint invocation returns empty body

### ISSUE THREAD

**Issue by AvikantSrivastava** [aws/sagemaker-xgboost-container#332]
<img width="702" alt="image" src="https://user-images.githubusercontent.com/41926176/191598517-19672d9b-e239-4d04-9b4c-9f826ca6f4d5.png">

**Comment by NikhilRaverkar** [comment]
You can see the examples of `invoke_endpoint` using [boto APIs](https://sagemaker-examples.readthedocs.io/en/latest/advanced_functionality/multi_model_xgboost_home_value/xgboost_multi_model_endpoint_home_value.html#Using-Boto-APIs-to-invoke-the-endpoint or using the [Sagemaker session](https://sagemaker-examples.readthedocs.io/en/latest/introduction_to_amazon_algorithms/xgboost_abalone/xgboost_abalone_dist_script_mode.html#Deploy-the-XGBoost-model)

**Comment by qmaruf** [comment]
Any update about this issue?

In my case, `invoke_endpoint` only works if I deploy it from the sagemaker lab notebook. If it's deployed from the local machine, the response body becomes empty!
