### ISSUE TITLE
IndexError on endpoint deployment

### ISSUE THREAD

**Issue by MetelStairs** [aws/sagemaker-xgboost-container#341]
Getting this error when deploying a model to an endpoint on SageMaker, not sure what might be causing it? Maybe wrong model directory, hoping someone can point me in the right direction?

```
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/algorithm_mode/serve.py", line 71, in load_model
    cls.booster, cls.format = serve_utils.get_loaded_booster(ScoringService.MODEL_PATH, ensemble)
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/algorithm_mode/serve_utils.py", line 192, in get_loaded_booster
    return (models, model_formats) if ensemble and len(models) > 1 else (models[0], model_formats[0])

IndexError: list index out of range
```

**Comment by mabunday** [comment]
Hi, thanks for the issue.

Can you confirm the version of XGB container that's being used? At a glance it looks like it isn't able to find the model file and is likely failing here `else (models[0], model_formats[0])`

**Comment by MetelStairs** [comment]
Hi there, the version used is 1.51-1. Would it be the path its being inputted then causing this?

**Comment by mabunday** [comment]
Yeah, likely there are no model files in the directory that's being loaded. The directory the algorithm is trying to load from should be logged if the iterator `full_model_paths` is not empty. See: https://github.com/aws/sagemaker-xgboost-container/blob/master/src/sagemaker_xgboost_container/algorithm_mode/serve_utils.py#L173

There's definitely an improvement that can be made to the error messaging here if the iterator is empty. I'll take up an action item for that, but in the meantime please double check how you're specifying the model(s) the endpoint should be using.

**Comment by MetelStairs** [comment]
I see, thanks!
